title: "Benjamin Abijah"
author: "Ben Abijah"
description: "&copy; 2025 Ben Abijah"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "About", file: "index.md"}
  - {title: "Resume", url: "/assets/images/benabijah.pdf"}
  - {title: "Publications", file: "pubs.md"}
  - {title: "Projects", file: "proj.md"}
  - {title: "Blogs", file: "blog.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:benabijah@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/benabijah"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/benjamin-abakah-abijah-936023126/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
